#
#数据库地址
#
datasource:
  jdbcUrl: jdbc:mysql://localhost:3306/mypet_social?#useUnicode=true&noAccessToProcedureBodies=true
  user: root
  password: houzhijia
  driverClass: com.mysql.jdbc.Driver
#
#mybatis
#
mybatis:
  config: classpath:Mybatis-config.xml
  mapperLocation: classpath:mapper/*.xml
#
#日志地址
#
logging:
  config: classpath:logback.xml
  path: ./logs